export { default as 더블_에스프레소_칩_프라푸치노 } from './더블_에스프레소_칩_프라푸치노.jpeg';
export { default as 모카_프라푸치노 } from './모카_프라푸치노.jpeg';
export { default as 바닐라_크림_프라푸치노 } from './바닐라_크림_프라푸치노.jpeg';
export { default as 에스프레소_프라푸치노 } from './에스프레소_프라푸치노.jpeg';
export { default as 자바_칩_프라푸치노 } from './자바_칩_프라푸치노.jpeg';
export { default as 제주_까망_크림_프라푸치노 } from './제주_까망_크림_프라푸치노.jpeg';
export { default as 제주_쑥떡_크림_프라푸치노 } from './제주_쑥떡_크림_프라푸치노 .jpeg';
export { default as 제주_유기농_말차로_만든_크림_프라푸치노 } from './제주_유기농_말차로_만든_크림_프라푸치노.jpeg';
export { default as 초콜릿_크림_칩_프라푸치노 } from './초콜릿_크림_칩_프라푸치노.jpeg';
export { default as 카라멜_프라푸치노 } from './카라멜_프라푸치노.jpeg';
export { default as 화이트_초콜릿_모카_프라푸치노 } from './화이트_초콜릿_모카_프라푸치노.jpeg';
export { default as 화이트_타이거_프라푸치노 } from './화이트_타이거_프라푸치노.jpeg';
